### 
GET https://localhost:5001/api/funcionario/listar

### 
POST https://localhost:5001/api/funcionario/cadastrar
Content-Type: application/json

{
    "nome" : "Hugo Cabral",
    "cpf" : "12347"
}

### 
GET https://localhost:5001/api/funcionario/buscar/123

### 
DELETE https://localhost:5001/api/funcionario/deletar/123456789

### 
PATCH  https://localhost:5001/api/funcionario/alterar
Content-Type: application/json

{
    "nome" : "Pedro Alvares Cabral",
    "cpf" : "123"
}