### 
GET https://localhost:5001/api/funcionario/listar

### 
POST https://localhost:5001/api/funcionario/cadastrar
Content-Type: application/json

{
    "nome" : "Astral Cabral",
    "cpf" : "88888888888",
    "Email" : "qwerty@gmail.com",
    "Salario" :  "1.000"
}

### 
GET https://localhost:5001/api/funcionario/buscar/1234778989

### 
DELETE https://localhost:5001/api/funcionario/deletar/2

### 
PATCH  https://localhost:5001/api/funcionario/alterar
Content-Type: application/json

{
    "nome" : "AB Cabral",
    "cpf" : "12"
}