### 
GET https://localhost:5001/api/funcionario/listar

### 
POST https://localhost:5001/api/funcionario/cadastrar
Content-Type: application/json

{
    "nome" : "Tomas Cabral",
    "cpf" : "1234778989"
}

### 
GET https://localhost:5001/api/funcionario/buscar/1234778989

### 
DELETE https://localhost:5001/api/funcionario/deletar/1234778989

### 
PATCH  https://localhost:5001/api/funcionario/alterar
Content-Type: application/json

{
    "nome" : "Pedro Alvares Cabral",
    "cpf" : "123"
}